### ISSUE TITLE
Project Dead? Make fork the new official version?

### ISSUE THREAD

**Issue by BryanQuigley** [cph6/zsync#15]
I spent some trying to build the current version of zsync here - and gave up.  Turns out https://github.com/NiLuJe/zsync -s version builds fine!

@NiLuJe and @krichter722 - you are the only ones who (I can see) have been trying to help make zsync better. @NiLuJe as you already have the repo that works well - do you want to be the new maintainer? (I have no official version designation ability - but can work to make it become apparent)

**Comment by NiLuJe** [comment]
We've moved on to [zsync2](https://github.com/NiLuJe/zsync2), and I still haven't found a place he time to propose our changes upstream, so that should tell you all you need to know about know about that ;).
